apiVersion: apps/v1
kind: Deployment
metadata:
  name: galsenai-demo-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      model: salary-prediction
  template:
    metadata:
      labels:
        model: salary-prediction
    spec:
      containers:
        - name: galsenai-salary-prediction
          image: papihack/galsenai-salary-prediction
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 5000
              name: http
